# NH3 分解 Ni(111) 体系 — VASP 输入文件生成器
# Author: Hermes Agent (for Liu Diru)
# Usage: python3 generate_inputs.py

import os
import itertools

# ============================================
# 配置参数
# ============================================

# 掺杂元素列表
DOPANTS = [
    'Sc', 'Ti', 'V', 'Cr', 'Fe', 'Co', 'Ni',  # 纯 Ni 作为基准
    'Cu', 'Zn', 'Ga', 'Mo', 'Ru', 'Rh', 'Pd', 'Ag',
    # 可以扩展到更多
]

# Ni(111) p(3x3) 晶胞参数
# Ni 晶格常数 (PBE optimized): a = 3.524 A
A = 3.524
C = 24.0  # 真空层 ~20A + slab ~4A

# POSCAR 模板
POSCAR_TEMPLATE = """Ni(111) p(3x3) - {dopant} doped
   1.00000000000000
     1.5000000000   -2.5980762114    0.0000000000
     1.5000000000    2.5980762114    0.0000000000
     0.0000000000    0.0000000000    {c:.6f}
   {n_ni}  {n_dop}
Direct
{positions}
"""

# INCAR 模板
INCAR_TEMPLATE = """# NH3 Decomposition - {dopant} doped Ni(111) - {job_type}
# Generated by Hermes Agent

SYSTEM = {system_name}

# Start parameters
ISTART = 0
ICHARG = 2
INIWAV = 1
PREC = Normal
ENCUT = 450
EDIFF = 1E-5
EDIFFG = -0.02

# Ionic relaxation
NSW = 100
IBRION = 2
ISIF = 2
ISMEAR = 1
SIGMA = 0.20

# Electronic
ALGO = Fast
LREAL = Auto
NPAR = 4

# Spin
ISPIN = 2
MAGMOM = 36*5.0

# DOS / Projection (for d-band center)
LORBIT = 11
RWIGS = 1.28 1.28  # Ni Ni (approximate)

# VDW
IVDW = 11
"""

# INCAR: 吸附质计算 (N atom adsorption)
INCAR_ADS = """# NH3 Decomposition - {dopant} doped Ni(111) - N adsorption
# Generated by Hermes Agent

SYSTEM = {system_name}

# Start parameters
ISTART = 0
ICHARG = 2
INIWAV = 1
PREC = Normal
ENCUT = 450
EDIFF = 1E-5
EDIFFG = -0.02

# Ionic relaxation
NSW = 200
IBRION = 2
ISIF = 0
ISMEAR = 1
SIGMA = 0.20

# Electronic
ALGO = Fast
LREAL = Auto
NPAR = 4

# Spin
ISPIN = 2
MAGMOM = 36*5.0 1.0  # + N atom

# VDW
IVDW = 11
"""

# INCAR: NEB (过渡态搜索)
INCAR_NEB = """# NH3 Decomposition - {dopant} doped Ni(111) - NEB
# Generated by Hermes Agent

SYSTEM = {system_name}

# Start parameters
ISTART = 0
ICHARG = 2
INIWAV = 1
PREC = Normal
ENCUT = 450
EDIFF = 1E-5
EDIFFG = -0.02

# NEB
IBRION = 3
ISIF = 0
SPRING = -5
IMAGES = 5
NSW = 100

# Electronic
ISMEAR = 1
SIGMA = 0.20
LREAL = Auto
ALGO = Fast
NPAR = 4

# Spin
ISPIN = 2
MAGMOM = 36*5.0 1.0

# VDW
IVDW = 11
"""

# KPOINTS
KPOINTS_CONTENT = """k-points for Ni(111) p(3x3)
Gamma-centered
  3  3  1
0  0  0
"""

# ============================================
# 辅助函数
# ============================================

def generate_ni111_poscar(ni_sites, dopant, replace_idx=0):
    """
    生成 Ni(111) p(3x3) slab 的 POSCAR.
    3 层，每层 9 个 Ni 原子。
    第 replace_idx 个表面原子替换为 dopant.
    """
    # Ni(111) 原子坐标（分数坐标）
    # Layer 1 (bottom), Layer 2, Layer 3 (surface)
    layer1 = [
        (0.00000, 0.00000, 0.08000),
        (0.33333, 0.16667, 0.08000),
        (0.66667, 0.33333, 0.08000),
        (0.00000, 0.33333, 0.08000),
        (0.33333, 0.50000, 0.08000),
        (0.66667, 0.66667, 0.08000),
        (0.00000, 0.66667, 0.08000),
        (0.33333, 0.83333, 0.08000),
        (0.66667, 0.00000, 0.08000),
    ]
    layer2 = [
        (0.11111, 0.22222, 0.14667),
        (0.44444, 0.38889, 0.14667),
        (0.77778, 0.55556, 0.14667),
        (0.11111, 0.55556, 0.14667),
        (0.44444, 0.72222, 0.14667),
        (0.77778, 0.88889, 0.14667),
        (0.11111, 0.88889, 0.14667),
        (0.44444, 0.05556, 0.14667),
        (0.77778, 0.22222, 0.14667),
    ]
    layer3 = [
        (0.00000, 0.00000, 0.21333),
        (0.33333, 0.16667, 0.21333),
        (0.66667, 0.33333, 0.21333),
        (0.00000, 0.33333, 0.21333),
        (0.33333, 0.50000, 0.21333),
        (0.66667, 0.66667, 0.21333),
        (0.00000, 0.66667, 0.21333),
        (0.33333, 0.83333, 0.21333),
        (0.66667, 0.00000, 0.21333),
    ]
    
    all_atoms = []
    for (x, y, z) in layer1:
        all_atoms.append(('Ni', x, y, z))
    for (x, y, z) in layer2:
        all_atoms.append(('Ni', x, y, z))
    
    # 第三层（表面层），第 replace_idx 个替换为掺杂原子
    for i, (x, y, z) in enumerate(layer3):
        if i == replace_idx and dopant != 'Ni':
            all_atoms.append((dopant, x, y, z))
        else:
            all_atoms.append(('Ni', x, y, z))
    
    # 统计原子数
    n_ni = sum(1 for a in all_atoms if a[0] == 'Ni')
    n_dop = sum(1 for a in all_atoms if a[0] != 'Ni')
    
    # 格式化为 POSCAR
    lines = []
    lines.append(f"Ni(111) p(3x3) - {dopant} doped")
    lines.append("   1.00000000000000")
    lines.append(f"     {1.5*A:.6f}    {-2.5980762114*A*0.57735:.6f}    0.0000000000")
    lines.append(f"     {1.5*A:.6f}    {2.5980762114*A*0.57735:.6f}    0.0000000000")
    lines.append(f"     0.0000000000    0.0000000000    {C:.6f}")
    
    if n_dop > 0:
        lines.append(f"  {n_ni}  {n_dop}")
    else:
        lines.append(f"  {n_ni}")
    
    lines.append("Selective Dynamics")
    lines.append("Direct")
    
    for i, (elem, x, y, z) in enumerate(all_atoms):
        # 底层两层固定，表面层（第三层）可动
        if i < 18:  # layer 1 + layer 2
            lines.append(f"  {x:.8f}  {y:.8f}  {z:.8f}  F  F  F")
        else:
            lines.append(f"  {x:.8f}  {y:.8f}  {z:.8f}  T  T  T")
    
    return '\n'.join(lines)


def write_potcar(elements):
    """
    生成 POTCAR 文件（需要事先准备好 POTCAR 库）
    实际使用需要连接 POTCAR 库路径
    """
    lines = []
    for elem in elements:
        lines.append(f"# POTCAR for {elem}")
    return '\n'.join(lines) + '\n# NOTE: 需要从 POTCAR 库中 cat 对应的 POTCAR 文件'


# ============================================
# 主程序：生成所有输入文件
# ============================================

def main():
    base_dir = "nh3_screening"
    
    for dopant in DOPANTS:
        if dopant == 'Ni':
            dir_name = f"{base_dir}/pure_Ni"
        else:
            dir_name = f"{base_dir}/Ni_{dopant}"
        
        os.makedirs(dir_name, exist_ok=True)
        
        # --- 裸 slab (bare) ---
        bare_dir = f"{dir_name}/01_bare"
        os.makedirs(bare_dir, exist_ok=True)
        
        poscar = generate_ni111_poscar(27, dopant)
        with open(f"{bare_dir}/POSCAR", 'w') as f:
            f.write(poscar)
        
        with open(f"{bare_dir}/INCAR", 'w') as f:
            f.write(INCAR_TEMPLATE.format(
                dopant=dopant,
                job_type="bare",
                system_name=f"Ni111_{dopant}_bare"
            ))
        
        with open(f"{bare_dir}/KPOINTS", 'w') as f:
            f.write(KPOINTS_CONTENT)
        
        # POTCAR 占位符
        elements = sorted(set(['Ni', dopant])) if dopant != 'Ni' else ['Ni']
        with open(f"{bare_dir}/POTCAR", 'w') as f:
            f.write(f"# POTCAR for {' '.join(elements)}\n")
            f.write("# Run: cat $POTCAR_LIB/POTCAR_{element1} $POTCAR_LIB/POTCAR_{element2} > POTCAR\n")
        
        # --- N 吸附 (N_ads) ---
        ads_dir = f"{dir_name}/02_N_ads"
        os.makedirs(ads_dir, exist_ok=True)
        
        # 复制 POSCAR 并加上 N 原子（手动放置 N 到 fcc hollow 位）
        with open(f"{ads_dir}/POSCAR", 'w') as f:
            f.write(poscar)  # 需要手动添加 N 原子并微调位置
        
        with open(f"{ads_dir}/INCAR", 'w') as f:
            f.write(INCAR_ADS.format(
                dopant=dopant,
                job_type="N_ads",
                system_name=f"Ni111_{dopant}_N_ads"
            ))
        
        with open(f"{ads_dir}/KPOINTS", 'w') as f:
            f.write(KPOINTS_CONTENT)
        
        # --- 提交脚本 (Slurm) ---
        sub_dir = dir_name
        with open(f"{sub_dir}/run_vasp.sh", 'w') as f:
            f.write(f"""#!/bin/bash
#SBATCH -J NH3_{dopant}
#SBATCH -N 1
#SBATCH -n 32
#SBATCH -t 48:00:00

module load vasp/6.4

# Step 1: Bare slab relaxation
cd 01_bare
mpirun vasp_std
cd ..

# Step 2: N adsorption
cd 02_N_ads
mpirun vasp_std
cd ..

echo "Done: {dopant} on Ni(111)"
""")
        
        print(f"✅ Generated: {dir_name}")

if __name__ == "__main__":
    main()
    print("\n🎉 All input files generated!")
    print("📁 Directory: ./nh3_screening/")
    print("")
    print("Next steps:")
    print("  1. Copy POTCAR files from your library")
    print("  2. Place N atom at fcc hollow site in 02_N_ads/POSCAR")
    print("  3. Submit: sbatch run_vasp.sh")
